### ISSUE TITLE
what is the difference between botscript and headless browser ?

### ISSUE THREAD

**Issue by dotkt** [makielskis/botscript#1]
what is the difference between botscript and headless browser ?

**Comment by felixguendling** [comment]
BotScript is much more simple and does not support JavaScript (and never will). On the other hand, BotScript is much more resource efficient (memory, CPU) so you can automate thousands of activities in parallel. If you want a real headless browser, you probably want to use a headless Chromium (e.g. puppeteer). But if you have some simple steps and need performance, BotScript might be a more efficient solution. BotScript allows to fake user agents and supports cookies and referrers.
